import = [
	"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
startup_mode = "Maximized"

opacity = 0.98
# blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13
