require 'keymaps'
require 'options'
require 'snippets'

require 'plugins/axtra'
require 'plugins/completion'
require 'plugins/format'
require 'plugins/fzflua'
require 'plugins/gitsigns'
require 'plugins/gopher'
require 'plugins/llm'
require 'plugins/mason'
require 'plugins/mini'
require 'plugins/treesitter'
