#!/usr/bin/env bash

input="${1:-region}"

hyprshot -m ${input} --raw |
    satty --filename - \
        --output-filename "$HOME/screenshots/$(date +'%Y-%m-%d-%H%M%S').png" \
        --early-exit \
        --actions-on-enter save-to-clipboard \
        --save-after-copy \
        --copy-command 'wl-copy'
